---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: 13

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list: recipe[tgw-server-base::default]
    attributes:
      tgw-server-base:
        install_dnsmasq: true
        install_chef_client: true
        install_kubeadm: true
        skip_selinux: true
