---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  product_version: 13

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list: recipe[server-base::default]
    attributes:
