---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 13

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list: recipe[server-base::default]
    attributes:
