inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'lib/kitchen/driver/*'
    - 'lib/kitchen/driver/docker/*'
    - 'Vagrantfile'
    - 'berks-cookbooks/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.6
Layout/ParameterAlignment:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

StringLiterals:
  Enabled: false